# Generated by Django 4.1 on 2022-08-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GI_Association_regestration",
            fields=[
                ("Appli_num", models.AutoField(primary_key=True, serialize=False)),
                ("name_of_applicant", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                (
                    "persons_products_organization_authority",
                    models.CharField(max_length=100),
                ),
                ("type_of_goods", models.CharField(max_length=100)),
                ("specification", models.CharField(max_length=100)),
                ("name_of_geographical_indications", models.CharField(max_length=100)),
                ("desc_of_goods", models.CharField(max_length=100)),
                ("geo_area", models.FloatField(max_length=100)),
                ("proof_of_origin", models.CharField(max_length=100)),
                ("method_of_production", models.CharField(max_length=100)),
                ("uniqueness", models.CharField(max_length=100)),
                ("inspection_body", models.CharField(max_length=100)),
                ("other", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=20)),
                ("is_deleted", models.BooleanField(default=False)),
                ("form_type", models.CharField(max_length=20)),
                ("date_of_regestration", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GI_User_reges",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=100)),
                ("address_of_user", models.CharField(max_length=100)),
                ("email_id", models.CharField(max_length=100)),
                ("ph_num", models.CharField(max_length=100)),
                ("gi_number", models.CharField(max_length=100)),
                ("date_of_registration", models.DateField(auto_now_add=True)),
                (
                    "Association_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.gi_association_regestration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="User2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfileInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("portfolio_site", models.URLField(blank=True)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, upload_to="profile_pics"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="main.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GI_User_renual",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=100)),
                ("ph_num", models.CharField(max_length=100)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.gi_user_reges",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GI_User_application_status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("date_created", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.gi_user_reges",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GI_Association_application_status",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=100)),
                ("ph_num", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("is_deleted", models.BooleanField(default=False)),
                ("form_type", models.CharField(max_length=20)),
                (
                    "assoc_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.gi_association_regestration",
                    ),
                ),
            ],
        ),
    ]
