# Generated by Django 4.1 on 2022-08-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="gi_user_reges", name="gi_number",),
    ]
