# Generated by Django 4.1 on 2022-08-25 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GIAssociatationRegistrationModel",
            fields=[
                (
                    "application_number",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name_of_applicant", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                (
                    "persons_products_organization_authority",
                    models.CharField(max_length=100),
                ),
                ("type_of_goods", models.CharField(max_length=100)),
                ("specification", models.CharField(max_length=100)),
                ("name_of_geographical_indications", models.CharField(max_length=100)),
                ("desc_of_goods", models.CharField(max_length=100)),
                ("geo_area", models.FloatField(max_length=100)),
                ("proof_of_origin", models.CharField(max_length=100)),
                ("method_of_production", models.CharField(max_length=100)),
                ("uniqueness", models.CharField(max_length=100)),
                ("inspection_body", models.CharField(max_length=100)),
                ("other", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "APPLIED"),
                            ("verified", "VERIFIED"),
                            ("approved", "APPROVED"),
                        ],
                        default="applied",
                        max_length=10,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("form_type", models.CharField(max_length=20)),
                ("date_of_regestration", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="gi_association_application_status",
            name="assoc_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.giassociatationregistrationmodel",
            ),
        ),
        migrations.AlterField(
            model_name="gi_user_reges",
            name="Association_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.giassociatationregistrationmodel",
            ),
        ),
        migrations.DeleteModel(name="Gi_Associatation_registration",),
    ]
