# Generated by Django 4.1 on 2022-08-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GIGI1A",
            fields=[
                ("Appli_num", models.IntegerField(primary_key=True, serialize=False)),
                ("name_of_applicant", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                (
                    "persons_products_organization_authority",
                    models.CharField(max_length=100),
                ),
                ("type_of_goods", models.CharField(max_length=100)),
                ("specification", models.CharField(max_length=100)),
                ("name_of_geographical_indications", models.CharField(max_length=100)),
                ("desc_of_goods", models.CharField(max_length=100)),
                ("geo_area", models.CharField(max_length=100)),
                ("proof_of_origin", models.CharField(max_length=100)),
                ("method_of_production", models.CharField(max_length=100)),
                ("uniqueness", models.CharField(max_length=100)),
                ("inspection_body", models.CharField(max_length=100)),
                ("other", models.CharField(max_length=100)),
            ],
        ),
    ]
