# Generated by Django 4.1 on 2022-08-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_gi_user_reges_gi_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="gi_user_reges",
            name="accociation_comments",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gi_user_reges",
            name="is_association_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gi_user_reges",
            name="is_officer_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gi_user_reges",
            name="officer_comments",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
