# Generated by Django 4.1 on 2022-08-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_giassociatationregistrationmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giassociatationregistrationmodel",
            name="form_type",
            field=models.CharField(
                choices=[
                    ("a", "Single Class"),
                    ("b", "Single Class Foreign Country"),
                    ("c", "Multiple Class"),
                    ("d", "Multiple Class Foreign Country"),
                ],
                default="a",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="giassociatationregistrationmodel",
            name="geo_area",
            field=models.CharField(max_length=100),
        ),
    ]
