# Generated by Django 4.1 on 2022-08-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_gi_association_application_status_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GI_Association_regestration",
            new_name="Gi_Associatation_registration",
        ),
        migrations.RemoveField(
            model_name="gi_association_application_status", name="form_type",
        ),
    ]
