# Generated by Django 4.1 on 2022-08-26 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_gi_user_reges_accociation_comments_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gi_user_reges", old_name="user_id", new_name="id",
        ),
        migrations.AddField(
            model_name="gi_user_reges",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
