# Generated by Django 4.1 on 2022-08-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_giassociatationregistrationmodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="giassociatationregistrationmodel",
            name="gi_tag",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
