# Generated by Django 4.1 on 2022-08-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_userprofileinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="GI_Assoctiation_renewal",
            fields=[
                ("renewal_num", models.AutoField(primary_key=True, serialize=False)),
                ("name_of_applicant", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="GI_User_reges",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="GI_User_renual",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name="GIGI1", new_name="GI_Association_regestration",
        ),
    ]
